INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (1, 'Afghanistan', 'AF', '93', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (2, 'Albania', 'AL', '355', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (3, 'Germany', 'DE', '49', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (4, 'Andorra', 'AD', '376', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (5, 'Angola', 'AO', '244', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (6, 'Anguilla', 'AI', '1 264', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (7, 'Antarctica', 'AQ', '672', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (8, 'Antigua and Barbuda', 'AG', '1 268', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (9, 'Saudi Arabia', 'SA', '966', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (10, 'Algeria', 'DZ', '213', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (11, 'Argentina', 'AR', '54', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (12, 'Armenia', 'AM', '374', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (13, 'Aruba', 'AW', '297', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (14, 'Australia', 'AU', '61', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (15, 'Austria', 'AT', '43', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (16, 'Azerbaijan', 'AZ', '994', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (17, 'Belgium', 'BE', '32', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (18, 'Bahamas', 'BS', '1 242', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (19, 'Bahrain', 'BH', '973', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (20, 'Bangladesh', 'BD', '880', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (21, 'Barbados', 'BB', '1 246', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (22, 'Belize', 'BZ', '501', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (23, 'Benin', 'BJ', '229', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (24, 'Bhutan', 'BT', '975', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (25, 'Belarus', 'BY', '375', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (26, 'Myanmar', 'MM', '95', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (27, 'Bolivia', 'BO', '591', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (28, 'Bonaire', 'BQ', '535', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (29, 'Bosnia and Herzegovina', 'BA', '387', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (30, 'Botswana', 'BW', '267', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (31, 'Brazil', 'BR', '55', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (32, 'Brunei', 'BN', '673', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (33, 'Bulgaria', 'BG', '359', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (34, 'Burkina Faso', 'BF', '226', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (35, 'Burundi', 'BI', '257', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (36, 'Cape Verde', 'CV', '238', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (37, 'Cambodia', 'KH', '855', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (38, 'Cameroon', 'CM', '237', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (39, 'Canada', 'CA', '1', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (40, 'Chad', 'TD', '235', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (41, 'Chile', 'CL', '56', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (42, 'China', 'CN', '86', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (43, 'Cyprus', 'CY', '357', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (44, 'Vatican City State', 'VA', '39', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (45, 'Colombia', 'CO', '57', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (46, 'Comoros', 'KM', '269', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (47, 'Republic of the Congo', 'CG', '242', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (48, 'Democratic Republic of the Congo', 'CD', '243', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (49, 'North Korea', 'KP', '850', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (50, 'South Korea', 'KR', '82', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (51, 'Ivory Coast', 'CI', '225', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (52, 'Costa Rica', 'CR', '506', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (53, 'Croatia', 'HR', '385', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (54, 'Cuba', 'CU', '53', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (55, 'Curaçao', 'CW', '5999', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (56, 'Denmark', 'DK', '45', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (57, 'Dominica', 'DM', '1 767', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (58, 'Ecuador', 'EC', '593', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (59, 'Egypt', 'EG', '20', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (60, 'El Salvador', 'SV', '503', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (61, 'United Arab Emirates', 'AE', '971', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (62, 'Eritrea', 'ER', '291', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (63, 'Slovakia', 'SK', '421', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (64, 'Slovenia', 'SI', '386', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (65, 'Spain', 'ES', '34', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (66, 'United States of America', 'US', '1', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (67, 'Estonia', 'EE', '372', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (68, 'Ethiopia', 'ET', '251', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (69, 'Philippines', 'PH', '63', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (70, 'Finland', 'FI', '358', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (71, 'Fiji', 'FJ', '679', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (72, 'France', 'FR', '33', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (73, 'Gabon', 'GA', '241', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (74, 'Gambia', 'GM', '220', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (75, 'Georgia', 'GE', '995', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (76, 'Ghana', 'GH', '233', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (77, 'Gibraltar', 'GI', '350', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (78, 'Grenada', 'GD', '1 473', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (79, 'Greece', 'GR', '30', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (80, 'Greenland', 'GL', '299', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (81, 'Guadeloupe', 'GP', '590', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (82, 'Guam', 'GU', '1 671', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (83, 'Guatemala', 'GT', '502', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (84, 'French Guiana', 'GF', '594', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (85, 'Guernsey', 'GG', '44', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (86, 'Guinea', 'GN', '224', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (87, 'Equatorial Guinea', 'GQ', '240', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (88, 'Guinea-Bissau', 'GW', '245', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (89, 'Guyana', 'GY', '592', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (90, 'Haiti', 'HT', '509', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (91, 'Honduras', 'HN', '504', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (92, 'Hong Kong', 'HK', '852', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (93, 'Hungary', 'HU', '36', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (94, 'India', 'IN', '91', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (95, 'Indonesia', 'ID', '62', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (96, 'Iran', 'IR', '98', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (97, 'Iraq', 'IQ', '964', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (98, 'Ireland', 'IE', '353', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (99, 'Bouvet Island', 'BV', NULL, 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (100, 'Isle of Man', 'IM', '44', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (101, 'Christmas Island', 'CX', '61', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (102, 'Norfolk Island', 'NF', '672', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (103, 'Iceland', 'IS', '354', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (104, 'Bermuda Islands', 'BM', '1 441', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (105, 'Cayman Islands', 'KY', '1 345', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (106, 'Cocos (Keeling) Islands', 'CC', '61', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (107, 'Cook Islands', 'CK', '682', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (108, 'Åland Islands', 'AX', '358', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (109, 'Faroe Islands', 'FO', '298', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (110, 'South Georgia and the South Sandwich Islands', 'GS', '500', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (111, 'Heard Island and McDonald Islands', 'HM', NULL, 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (112, 'Maldives', 'MV', '960', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (113, 'Falkland Islands (Malvinas)', 'FK', '500', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (114, 'Northern Mariana Islands', 'MP', '1 670', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (115, 'Marshall Islands', 'MH', '692', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (116, 'Pitcairn Islands', 'PN', '870', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (117, 'Solomon Islands', 'SB', '677', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (118, 'Turks and Caicos Islands', 'TC', '1 649', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (119, 'United States Minor Outlying Islands', 'UM', '246', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (120, 'Virgin Islands', 'VG', '1 284', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (121, 'United States Virgin Islands', 'VI', '1 340', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (122, 'Israel', 'IL', '972', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (123, 'Italy', 'IT', '39', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (124, 'Jamaica', 'JM', '1 876', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (125, 'Japan', 'JP', '81', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (126, 'Jersey', 'JE', '44', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (127, 'Jordan', 'JO', '962', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (128, 'Kazakhstan', 'KZ', '7', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (129, 'Kenya', 'KE', '254', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (130, 'Kyrgyzstan', 'KG', '996', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (131, 'Kiribati', 'KI', '686', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (132, 'Kuwait', 'KW', '965', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (133, 'Lebanon', 'LB', '961', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (134, 'Laos', 'LA', '856', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (135, 'Lesotho', 'LS', '266', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (136, 'Latvia', 'LV', '371', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (137, 'Liberia', 'LR', '231', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (138, 'Libya', 'LY', '218', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (139, 'Liechtenstein', 'LI', '423', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (140, 'Lithuania', 'LT', '370', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (141, 'Luxembourg', 'LU', '352', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (142, 'Mexico', 'MX', '52', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (143, 'Monaco', 'MC', '377', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (144, 'Macao', 'MO', '853', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (145, 'Macedonia', 'MK', '389', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (146, 'Madagascar', 'MG', '261', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (147, 'Malaysia', 'MY', '60', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (148, 'Malawi', 'MW', '265', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (149, 'Mali', 'ML', '223', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (150, 'Malta', 'MT', '356', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (151, 'Morocco', 'MA', '212', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (152, 'Martinique', 'MQ', '596', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (153, 'Mauritius', 'MU', '230', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (154, 'Mauritania', 'MR', '222', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (155, 'Mayotte', 'YT', '262', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (156, 'Estados Federados de', 'FM', '691', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (157, 'Moldova', 'MD', '373', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (158, 'Mongolia', 'MN', '976', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (159, 'Montenegro', 'ME', '382', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (160, 'Montserrat', 'MS', '1 664', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (161, 'Mozambique', 'MZ', '258', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (162, 'Namibia', 'NA', '264', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (163, 'Nauru', 'NR', '674', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (164, 'Nepal', 'NP', '977', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (165, 'Nicaragua', 'NI', '505', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (166, 'Niger', 'NE', '227', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (167, 'Nigeria', 'NG', '234', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (168, 'Niue', 'NU', '683', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (169, 'Norway', 'NO', '47', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (170, 'New Caledonia', 'NC', '687', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (171, 'New Zealand', 'NZ', '64', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (172, 'Oman', 'OM', '968', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (173, 'Netherlands', 'NL', '31', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (174, 'Pakistan', 'PK', '92', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (175, 'Palau', 'PW', '680', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (176, 'Palestine', 'PS', '970', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (177, 'Panama', 'PA', '507', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (178, 'Papua New Guinea', 'PG', '675', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (179, 'Paraguay', 'PY', '595', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (180, 'Peru', 'PE', '51', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (181, 'French Polynesia', 'PF', '689', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (182, 'Poland', 'PL', '48', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (183, 'Portugal', 'PT', '351', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (184, 'Puerto Rico', 'PR', '1', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (185, 'Qatar', 'QA', '974', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (186, 'United Kingdom', 'GB', '44', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (187, 'Central African Republic', 'CF', '236', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (188, 'Czech Republic', 'CZ', '420', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (189, 'Dominican Republic', 'DO', '1 809', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (190, 'South Sudan', 'SS', '211', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (191, 'Réunion', 'RE', '262', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (192, 'Rwanda', 'RW', '250', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (193, 'Romania', 'RO', '40', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (194, 'Russia', 'RU', '7', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (195, 'Western Sahara', 'EH', '212', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (196, 'Samoa', 'WS', '685', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (197, 'American Samoa', 'AS', '1 684', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (198, 'Saint Barthélemy', 'BL', '590', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (199, 'Saint Kitts and Nevis', 'KN', '1 869', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (200, 'San Marino', 'SM', '378', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (201, 'Saint Martin (French part)', 'MF', '1 599', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (202, 'Saint Pierre and Miquelon', 'PM', '508', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (203, 'Saint Vincent and the Grenadines', 'VC', '1 784', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (204, 'Ascensión y Tristán de Acuña', 'SH', '290', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (205, 'Saint Lucia', 'LC', '1 758', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (206, 'Sao Tome and Principe', 'ST', '239', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (207, 'Senegal', 'SN', '221', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (208, 'Serbia', 'RS', '381', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (209, 'Seychelles', 'SC', '248', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (210, 'Sierra Leone', 'SL', '232', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (211, 'Singapore', 'SG', '65', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (212, 'Sint Maarten', 'SX', '1 721', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (213, 'Syria', 'SY', '963', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (214, 'Somalia', 'SO', '252', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (215, 'Sri Lanka', 'LK', '94', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (216, 'South Africa', 'ZA', '27', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (217, 'Sudan', 'SD', '249', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (218, 'Sweden', 'SE', '46', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (219, 'Switzerland', 'CH', '41', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (220, 'Suriname', 'SR', '597', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (221, 'Svalbard and Jan Mayen', 'SJ', '47', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (222, 'Swaziland', 'SZ', '268', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (223, 'Tajikistan', 'TJ', '992', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (224, 'Thailand', 'TH', '66', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (225, 'Taiwan', 'TW', '886', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (226, 'Tanzania', 'TZ', '255', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (227, 'British Indian Ocean Territory', 'IO', '246', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (228, 'French Southern Territories', 'TF', NULL, 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (229, 'East Timor', 'TL', '670', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (230, 'Togo', 'TG', '228', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (231, 'Tokelau', 'TK', '690', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (232, 'Tonga', 'TO', '676', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (233, 'Trinidad and Tobago', 'TT', '1 868', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (234, 'Tunisia', 'TN', '216', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (235, 'Turkmenistan', 'TM', '993', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (236, 'Turkey', 'TR', '90', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (237, 'Tuvalu', 'TV', '688', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (238, 'Ukraine', 'UA', '380', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (239, 'Uganda', 'UG', '256', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (240, 'Uruguay', 'UY', '598', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (241, 'Uzbekistan', 'UZ', '998', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (242, 'Vanuatu', 'VU', '678', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (243, 'Venezuela', 'VE', '58', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (244, 'Vietnam', 'VN', '84', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (245, 'Wallis and Futuna', 'WF', '681', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (246, 'Yemen', 'YE', '967', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (247, 'Djibouti', 'DJ', '253', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (248, 'Zambia', 'ZM', '260', 'A');
INSERT INTO `c_countrys`(`id_country`, `name`, `code`, `phone_code`, `status`) VALUES (249, 'Zimbabwe', 'ZW', '263', 'A');
